name: Monitoraggio Biglietti Treno

on:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup di Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installazione delle dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Esecuzione dello script di monitoraggio
        # ▼▼▼ QUESTA SEZIONE DEVE CONTENERE TUTTE E 5 LE VARIABILI ▼▼▼
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MONITOR_URL: ${{ secrets.MONITOR_URL }}
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
          JSONBIN_ID: ${{ secrets.JSONBIN_ID }}
        run: python monitor_biglietti.py
