name: Report Prezzi Giornaliero

on:
  # Esegue lo script ogni giorno alle 17:00 UTC (19:00 ora italiana estiva)
  schedule:
    - cron: '0 17 * * *'
  
  # Permette di avviare lo script manualmente dalla tab "Actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup di Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installazione delle dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Esecuzione dello script di report
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python report_prezzi.py
