name: Monitoraggio Biglietti Treno

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup di Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installazione delle dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # ▼▼▼ SEZIONE DELLA CACHE MODIFICATA ▼▼▼
      - name: Cache dei file di stato
        uses: actions/cache@v3
        with:
          path: |
            dati_biglietti.txt
            ultima_notifica.txt
          # Chiave di ripristino: cerca la cache più recente
          key: ${{ runner.os }}-dati-script-${{ hashFiles('dati_biglietti.txt', 'ultima_notifica.txt') }}
          restore-keys: |
            ${{ runner.os }}-dati-script-

      - name: Esecuzione dello script di monitoraggio
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MONITOR_URL: ${{ secrets.MONITOR_URL }}
        run: python nome_del_tuo_script.py

