# Nome del workflow che apparirà nella tab "Actions" di GitHub
name: Scraper Trenitalia

on:
  # Permette di avviare il workflow manualmente dalla pagina Actions
  workflow_dispatch:

  # Esegue lo script automaticamente ogni giorno alle 7:00 UTC
  schedule:
    - cron: '0 7 * * *'

jobs:
  scrape:
    # Esegue il job su un server virtuale con l'ultima versione di Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Scarica il codice del tuo repository sul server virtuale
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Imposta l'ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installa le librerie Python necessarie
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r trequirements.txt
      
      # 4. Esegue lo script Python passando i secrets di Telegram
      - name: Run Python Scraper and Send Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python cerca_treni.py
